#!/bin/bash
#SBATCH --array=1-3%3
#SBATCH --error=/cluster/tufts/hugheslab/eharve06/slurmlog/err/log_%j.err
#SBATCH --gres=gpu:rtx_a6000:1
#SBATCH --mem=16g
#SBATCH --ntasks=4
#SBATCH --output=/cluster/tufts/hugheslab/eharve06/slurmlog/out/log_%j.out
#SBATCH --partition=hugheslab
#SBATCH --time=168:00:00

source ~/.bashrc
conda activate l3d_2024f_cuda12_1

# Define an array of commands [0-23]
experiments=(
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=1 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_163' --lr=0.1 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.1_pooling=Mean_seed=1001' --num_channels=2 --num_workers=4 --pooling='Mean' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=1 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_163' --lr=0.01 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.01_pooling=Mean_seed=1001' --num_channels=2 --num_workers=4 --pooling='Mean' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=1 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_163' --lr=0.001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.001_pooling=Mean_seed=1001' --num_channels=2 --num_workers=4 --pooling='Mean' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=1 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_163' --lr=0.0001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.0001_pooling=Mean_seed=1001' --num_channels=2 --num_workers=4 --pooling='Mean' --save --seed=1001 --weight_decay=0.0"



    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.1 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.1_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.1 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.1_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.1 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.1_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.01 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.01_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.01 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.01_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.01 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.01_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.001 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.001_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.001 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.001_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.001 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.001_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.0001 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.0001_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.0001 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.0001_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=1e-06 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.0001 --model='ViT-B/16' --model_name='alpha=1e-06_criterion=L2_lr=0.0001_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.1 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.1_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.1 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.1_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.1 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.1_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.01 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.01_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.01 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.01_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.01 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.01_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.001_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.001_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.001_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.0001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.0001_pooling=SmAP_seed=1001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=1001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.0001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.0001_pooling=SmAP_seed=2001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=2001 --weight_decay=0.0"
    "python ../src/fine-tune_oasis-3.py --alpha=0.0 --batch_size=4 --criterion='L2' --dataset_dir='/cluster/tufts/hugheslab/datasets/OASIS-3_MRI_numpy' --epochs=100 --experiments_dir='/cluster/tufts/hugheslab/eharve06/pooling/experiments/OASIS-3_MRI_ViT_B_16' --lr=0.0001 --model='ViT-B/16' --model_name='alpha=0.0_criterion=L2_lr=0.0001_pooling=SmAP_seed=3001' --num_channels=2 --num_workers=4 --pooling='SmAP' --save --seed=3001 --weight_decay=0.0"
)

eval "${experiments[$SLURM_ARRAY_TASK_ID]}"

conda deactivate